[package]
name = "cube3d"
description = "A console-based 3D cube rotation demo"
repository = "https://github.com/drewwalton19216801/cube3d"
readme = "README.md"
version = "0.5.99"
edition = "2021"
license = "MIT"

[dependencies]
druid = "0.8.3"
image = "0.25.2"
font8x8 = "0.3.1"