[package]
name = "cube3d"
description = "A console-based 3D cube rotation demo"
repository = "https://github.com/drewwalton19216801/cube3d"
readme = "README.md"
version = "0.5.0"
edition = "2021"
license = "MIT"

[dependencies]
druid = "0.8.3"